dist: trusty
sudo: required 

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-9
      - g++-9

os:
    - linux
    - osx

compiler:
    - gcc
    - clang
    
env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
    # Export CC and CXX to tell cmake which compiler to use
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=/usr/bin/gcc-9 && export CXX=/usr/bin/g++-9 && gcc -v && g++ -v && cmake --version; fi
    # run
    - mkdir build_cmake
    - cd build_cmake
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build . --config $BUILD_CONFIGURATION
    - ctest --output-on-failure